### ISSUE TITLE
Create TestMotor subsystem

### ISSUE THREAD

**Issue by nix342** [frc-88/TJ-MotorTester#2]

**Comment by rbtgagnon** [comment]
Great

**Comment by Dcox04** [comment]
Cool

**Comment by nix342** [comment]
Toggle brake mode

**Comment by nix342** [comment]
After discussion with Doug, we should assume the test motor will be a 775 Pro controlled by a TalonSRX.

**Comment by nix342** [comment]
I created a pull request based on Evan's fork and pulled in the code for the TestMotor class,
